### ISSUE TITLE
Great Site (Have to do this so doesn't show up in my email incase they check)

### ISSUE THREAD

**Issue by snowstudentDev** [Operation-Phoenix-Dawn/Operation-Phoenix-Dawn.github.io#2]
1 thing that should be added is having it open to a launcher of some kind this could be done via a HTML file download and using just a hard coded password but have the github.io site be in about blank its mad simple and the codes easy it just helps it not get blocked also make sure you add "mirrors" of the different games from different github accounts this can help with the ability to not block it

**Comment by Pokeknight2610** [comment]
Actually, this is a mirror as it got blocked on securly, the original is mr-milky-way.github.io

**Comment by burlingneta** [comment]
ok cool hi this is snowstudentdev on a different account I made a working launcher for this and am working on some other school qol tools that will be on the github of my original post

**Comment by Mr-milky-way** [comment]
@snowstudentDev I went ahead and added a button for it.

**Comment by Pokeknight2610** [comment]
Yup this should be resolved, it is on the games page

**Comment by snowstudentDev** [comment]
cool
