### ISSUE TITLE
Many games are broken

### ISSUE THREAD

**Issue by Pokeknight2610** [Operation-Phoenix-Dawn/Operation-Phoenix-Dawn.github.io#4]
1. https://operation-phoenix-dawn.github.io/games/fantasy-dash/
Gives me a 404
2. https://operation-phoenix-dawn.github.io/games/getaway-shootout/
Not fully updated and the unity webgl stuff is ugly (see my pull request)
3. https://operation-phoenix-dawn.github.io/games/undertale/
????? https://drive.google.com/file/d/1ie88RqryG4BJeP-lH7c4tds3toXgizIo/view?usp=sharing

Thats all for now bye

**Comment by Mr-milky-way** [comment]
Undertale is fixed and so is fantasy dash, I will work on getaway shootout.

**Comment by Pokeknight2610** [comment]
OK, this is fine for now
