### ISSUE TITLE
I suggest you remove undertale, or tell me where you found it

### ISSUE THREAD

**Issue by Pokeknight2610** [Operation-Phoenix-Dawn/Operation-Phoenix-Dawn.github.io#5]
You have blatantly stole Mecanix Creations assets in the game labled "Undertale." You can use the default version of mcxtale if you want, but you cannot claim it to be your own, referencing the logo with "Black Jesus Games" on it. I suggest you remove this logo, as Black Jesus Games does not own the rights to Mecanix assets and inform me where you got it from, or if it was yourself. If you do not reply by Monday, Mecanix Creations WILL request for you to take down mcxtale entirely.
Thank you for your time.

**Comment by Mr-milky-way** [comment]
https://github.com/MecanixCreations/McxTale2
look at LICENSE

**Comment by Pokeknight2610** [comment]
I have contacted him, and as we did not account for the possibility  others stealing our works, we will update the license accordingly

**Comment by Mr-milky-way** [comment]
> Are you Black Jesus Games?

No

**Comment by Pokeknight2610** [comment]
Where can i find him?

**Comment by Mr-milky-way** [comment]
I'm not sure where my friend got it.

**Comment by Pokeknight2610** [comment]
At this point I just want to find this madlad. If you can give me said friend's username that would be great

**Comment by Pokeknight2610** [comment]
Also, if you want the original (It also boots faster) here you go https://github.com/MecanixCreations/McxTale2/

**Comment by Mr-milky-way** [comment]
He doesn't have a github (that I know of), if you want me to take it down I will it's one of my least viewed pages.

**Comment by Pokeknight2610** [comment]
If you could replace it with the original that would be amazing, as I don't want this "Black Jesus Games" guy to be credited for my friend's hard work and suffering. He spent at least a week figuring out how to port undertale to web with many issues. I just don't want this guy to take credit for it.

**Comment by Pokeknight2610** [comment]
Also, i apologize for the harsh accusation and not being informed about the license sooner

**Comment by Mr-milky-way** [comment]
> Also, i apologize for the harsh accusation and not being informed about the license sooner

Nah it's good, I'm used to it by now.

**Comment by Mr-milky-way** [comment]
> If you could replace it with the original that would be amazing, as I don't want this "Black Jesus Games" guy to be credited for my friend's hard work and suffering. He spent at least a week figuring out how to port undertale to web with many issues. I just don't want this guy to take credit for it.

Ok

**Comment by Pokeknight2610** [comment]
Thanks again, good luck with the site!

**Comment by Pokeknight2610** [comment]
Still, may i ask, i would like to go down the black jesus games rabbit hole, can you give your friend's email, or ask him about it for me?

**Comment by Mr-milky-way** [comment]
> Still, may i ask, i would like to go down the black jesus games rabbit hole, can you give your friend's email, or ask him about it for me?

Yeah I will ask him; I looked at the differences of the game and it looks like he just changed the splash there was one called goofy games if that helps.

**Comment by Mr-milky-way** [comment]
@Pokeknight2610 He said that he saw the license and thought putting that on there would be funny, no harm intended. Hope this clears this up:)

**Comment by Pokeknight2610** [comment]
Ok. It makes for a zanier opening, which takes longer to load. It even crashed once and started making weird noises on my chromebook.
By the way you are using an old buggy build :D

**Comment by Mr-milky-way** [comment]
> By the way your friend added it to an old buggy build :D
Ok I will up date it, btw where did you get the source files for it?

**Comment by Pokeknight2610** [comment]
I don't know where he got the files to make it but you can find the html5 build here 
https://github.com/MecanixCreations/McxTale2
I heard you were upset about this (from Gabe), and I am sorry, I just don't want people to take credit for my friend's work.

**Comment by Mr-milky-way** [comment]
Yeah, if you got it from [this](https://github.com/TotallyTobyFox/undertale), I can't use it :( so just ask him.

**Comment by Pokeknight2610** [comment]
Oh damn. Thats unfortunate. There is something that could lead me to it ill keep you posted

**Comment by Pokeknight2610** [comment]
He used a decomp by danielah05. You should be fine? I read the license, and as he made a mod (edited textures) and didn't remove credit to the original we should be fine. By putting another logo of someone that contributed nothing, that is breaking the license.
(Link: https://github.com/danielah05/UndertaleDecomp)

**Comment by Mr-milky-way** [comment]
Ok, thank you

**Comment by Pokeknight2610** [comment]
In case you do update to current mcxtale I currently have a pull request open for editing the license, so wait a bit

**Comment by Pokeknight2610** [comment]
Alright the license is updated :D
